#print(150+5)
#print("Hola Mundo")
#print("This isn\'t a number")
#print('Este signo \\ es una barra invertida')
#print("Hay\nque hambre\n\tya no tengo")
#print("Barra Normal: /\nBarra Invertida: \\")
#print("A\tB\tC\nD\tE\tF\nG\tH\tI")
#print(input("¿En què paìs vives?"))
#print("Vamos crear un nombre a tu cerveza")
#print('El nombre de la cerveza es:\n "' + input("Cual es tu color favorito: ")+" "+ input("Que parte de tu cerveza te gusta: ") + '"\nFelicitaciones!')
print("Hola")